language: java
jdk:
  - openjdk14
install: true
script: mvn clean install
cache:
  directories:
    - $HOME/.m2
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE db_example;"
  - mysql -e "CREATE USER 'springuser'@'%';"
  - mysql -e "GRANT ALL PRIVILEGES ON db_example.* To 'springuser'@'%' IDENTIFIED BY 'ThePassword';"