server:
  port:
    8080
aws_database:
 rds_endpoint:
   "db-test.cfd9wfcv6fdx.ap-northeast-1.rds.amazonaws.com"
 rds_port:
   3306
 rds_name:
   "db-test"
 rds_username:
   "admin-Duncan"
 rds_password:
   "pH959&Fhx2*lP1nT"
 max_connections:
   10
mysql:
  driver:
    "com.mysql.jdbc.Driver"